---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: jet-vault-config
  labels:
    app: crossplane-provider-jet-vault
spec:
  image: registry.gitlab.com/ica1/paas/provider-jet-vault-controller-amd64:v0.1.0
  args: ["-d"]
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-jet-vault
spec:
  package: registry.gitlab.com/ica1/paas/provider-jet-vault-amd64:v0.1.0
  controllerConfigRef:
    name: jet-vault-config
