apiVersion: approle.vault.jet.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: hsbc-ma-preprod
spec:
  forProvider:
    roleName: hsbc-ma-preprod
    secretIdSecretRef:
      key: password
      name: my-custom-secret
      namespace: crossplane-system
    backend: approle