---
apiVersion: generic.vault.jet.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: test
spec:
  forProvider:
    deleteAllVersions: true
    path: "secret/customer-creds/hsbc/toto"
    dataJson: |
      {
        "foo": "bar",
        "pizza": "cheese"
      }